apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-kill-chaos
  namespace: chaos-engineering
spec:
  appinfo:
    appns: chaos-platform
    applabel: 'app=user-service'
    appkind: deployment
  chaosServiceAccount: litmus-admin
  monitoring: true
  jobCleanUpPolicy: 'retain'
  annotationCheck: 'false'
  engineState: 'active'
  chaosInterval: '2m'
  totalChaosDuration: '5m'
  rampTime: '1m'
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '60'
            - name: CHAOS_INTERVAL
              value: '30'
            - name: FORCE
              value: 'false'
            - name: PODS_AFFECTED_PERC
              value: '50' 